# CadEval Configuration
openscad:
  executable_path: /Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD
  minimum_version: '2021.01'
  render_timeout_seconds: 120
  export_format: asciistl
  backend: Manifold
  summary_options: all
directories:
  tasks: ./tasks
  reference: ./reference
  generated_outputs: ./generated_outputs
  results: ./results
  output: ./generated_outputs
llm:
  models:
  - name: o1-2024-12-17
    provider: openai
    temperature: 0.4
    max_tokens: 15000
  - name: claude-3-7-sonnet-20250219
    provider: anthropic
    temperature: 0.4
    max_tokens: 15000
  - name: gemini-2.5-pro-exp-03-25
    provider: google
    temperature: 0.4
    max_tokens: 15000
geometry_check:
  bounding_box_tolerance_mm: 0.5
  icp_fitness_threshold: 1.0
