{
    "run_id": "20250405_192806",
    "meta_statistics": {
        "gemini-2.0-flash": {
            "total_tasks": 10,
            "scad_gen_success_count": 10,
            "render_success_count": 9,
            "geo_check_run_success_count": 9,
            "all_geo_checks_passed_count": 6,
            "overall_pipeline_success_count": 5,
            "scad_gen_success_rate": 100.0,
            "render_success_rate_rel": 90.0,
            "geo_check_run_success_rate_rel": 100.0,
            "all_geo_checks_passed_rate_rel": 66.66666666666666,
            "overall_pipeline_success_rate": 50.0,
            "average_similarity_distance": 0.21970356193500556,
            "successful_similarity_count": 5,
            "median_similarity_distance": 0.22696369785240533,
            "stdev_similarity_distance": 0.10948224407847308
        }
    },
    "results_by_model": {
        "gemini-2.0-flash": [
            {
                "task_id": "task1",
                "model_name": "gemini-2.0-flash",
                "task_description": "A simple hex nut without the threads modeled. The nut has a hexagonal shape with a hole in the center of the hexagonal shape. The hexagon is 10mm wide (flat size to flat side). The hole diameter through the center of the hexagon is 5mm. The thickness of the nut is 5mm.",
                "reference_stl_path": "./reference/task1.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nA simple hex nut without the threads modeled. The nut has a hexagonal shape with a hole in the center of the hexagonal shape. The hexagon is 10mm wide (flat size to flat side). The hole diameter through the center of the hexagon is 5mm. The thickness of the nut is 5mm.\n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-2.0-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-05T19:28:19.946978",
                "output_scad_path": "results/20250405_192806/scad/task1_google_gemini_2.0_flash.scad",
                "output_stl_path": "results/20250405_192806/stl/task1_google_gemini_2.0_flash.stl",
                "output_summary_json_path": "results/20250405_192806/stl/task1_google_gemini_2.0_flash_summary.json",
                "render_status": "Success",
                "render_duration_seconds": 0.05982398986816406,
                "render_error_message": null,
                "checks": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": false
                },
                "geometric_similarity_distance": 1.0633855582778,
                "icp_fitness_score": 0.47058,
                "generation_error": null,
                "check_error": "AlignedBBoxCheck: Final Aligned vs Ref BBox Dims Diff (Sorted): ['0.0401', '4.3364', '5.9160'] exceeds tolerance 0.5",
                "scad_generation_success": true,
                "render_success": true,
                "render_status_detail": "Success",
                "geometry_check_orchestration_success": true,
                "individual_geometry_checks_passed": false,
                "individual_check_statuses": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": false
                },
                "geometry_check_error_detail": "AlignedBBoxCheck: Final Aligned vs Ref BBox Dims Diff (Sorted): ['0.0401', '4.3364', '5.9160'] exceeds tolerance 0.5",
                "overall_pipeline_success": false,
                "similarity_distance_detail": "1.0634"
            },
            {
                "task_id": "task10",
                "model_name": "gemini-2.0-flash",
                "task_description": "A square face swept along a half circle path to create a rainbow-like arc. The outer diameter of the rainbow is 130mm and the inner diameter is 70mm.\nThe square is 30mm x 30 mm. The half circle path is 100mm in diameter. And the center point of the square is along the path.",
                "reference_stl_path": "./reference/task10.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nA square face swept along a half circle path to create a rainbow-like arc. The outer diameter of the rainbow is 130mm and the inner diameter is 70mm.\nThe square is 30mm x 30 mm. The half circle path is 100mm in diameter. And the center point of the square is along the path.\n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-2.0-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-05T19:28:21.736548",
                "output_scad_path": "results/20250405_192806/scad/task10_google_gemini_2.0_flash.scad",
                "output_stl_path": "results/20250405_192806/stl/task10_google_gemini_2.0_flash.stl",
                "output_summary_json_path": "results/20250405_192806/stl/task10_google_gemini_2.0_flash_summary.json",
                "render_status": "Success",
                "render_duration_seconds": 0.03426980972290039,
                "render_error_message": null,
                "checks": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometric_similarity_distance": 0.32167146248136236,
                "icp_fitness_score": 1.0,
                "generation_error": null,
                "check_error": null,
                "scad_generation_success": true,
                "render_success": true,
                "render_status_detail": "Success",
                "geometry_check_orchestration_success": true,
                "individual_geometry_checks_passed": true,
                "individual_check_statuses": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometry_check_error_detail": null,
                "overall_pipeline_success": true,
                "similarity_distance_detail": "0.3217"
            },
            {
                "task_id": "task2",
                "model_name": "gemini-2.0-flash",
                "task_description": "This is a 3mm thickness rectangular plate. The plate is 18mm x 32mm in dimension.\nWhen looking down at the plate, it has two holes that are drilled through it.\nIn the bottom left of the plate, there\u2019s a hole with a centerpoint that is 3mm from the short (18mm) side and 3 mm from the long (32mm) side. This hole has a diameter of 2mm\nIn roughly the top left corner of plate, there\u2019s a hole of diameter 3mm. It\u2019s center point is 8mm from the short side (18mm side) and 6mm away from the long (32mm) side.",
                "reference_stl_path": "./reference/task2.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nThis is a 3mm thickness rectangular plate. The plate is 18mm x 32mm in dimension.\nWhen looking down at the plate, it has two holes that are drilled through it.\nIn the bottom left of the plate, there\u2019s a hole with a centerpoint that is 3mm from the short (18mm) side and 3 mm from the long (32mm) side. This hole has a diameter of 2mm\nIn roughly the top left corner of plate, there\u2019s a hole of diameter 3mm. It\u2019s center point is 8mm from the short side (18mm side) and 6mm away from the long (32mm) side.\n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-2.0-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-05T19:28:06.661719",
                "output_scad_path": "results/20250405_192806/scad/task2_google_gemini_2.0_flash.scad",
                "output_stl_path": "results/20250405_192806/stl/task2_google_gemini_2.0_flash.stl",
                "output_summary_json_path": "results/20250405_192806/stl/task2_google_gemini_2.0_flash_summary.json",
                "render_status": "Success",
                "render_duration_seconds": 0.06365633010864258,
                "render_error_message": null,
                "checks": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometric_similarity_distance": 0.10918501297834621,
                "icp_fitness_score": 0.99994,
                "generation_error": null,
                "check_error": null,
                "scad_generation_success": true,
                "render_success": true,
                "render_status_detail": "Success",
                "geometry_check_orchestration_success": true,
                "individual_geometry_checks_passed": true,
                "individual_check_statuses": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometry_check_error_detail": null,
                "overall_pipeline_success": true,
                "similarity_distance_detail": "0.1092"
            },
            {
                "task_id": "task3",
                "model_name": "gemini-2.0-flash",
                "task_description": "This is a 10mm thick circular plate. It\u2019s actually a concentric circle (sort of like a gasket). The outer diameter is  100mm and the inner diameter is 50mm. There are two holes through the plate. One hole is at the 12 o\u2019clock position (at the top of the plate). It\u2019s halfway between the inner diameter and outer diameter (so the center hole is 37.5mm from the center of the circular plate. The hole is 5mm diameter. The second hole is in the 3 o\u2019clock position. It\u2019s also half way between the inner and outer diameter of the plate. This hole is 10mm in diameter.",
                "reference_stl_path": "./reference/task3.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nThis is a 10mm thick circular plate. It\u2019s actually a concentric circle (sort of like a gasket). The outer diameter is  100mm and the inner diameter is 50mm. There are two holes through the plate. One hole is at the 12 o\u2019clock position (at the top of the plate). It\u2019s halfway between the inner diameter and outer diameter (so the center hole is 37.5mm from the center of the circular plate. The hole is 5mm diameter. The second hole is in the 3 o\u2019clock position. It\u2019s also half way between the inner and outer diameter of the plate. This hole is 10mm in diameter.\n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-2.0-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-05T19:28:08.548059",
                "output_scad_path": "results/20250405_192806/scad/task3_google_gemini_2.0_flash.scad",
                "output_stl_path": "results/20250405_192806/stl/task3_google_gemini_2.0_flash.stl",
                "output_summary_json_path": "results/20250405_192806/stl/task3_google_gemini_2.0_flash_summary.json",
                "render_status": "Success",
                "render_duration_seconds": 0.0606989860534668,
                "render_error_message": null,
                "checks": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": false
                },
                "geometric_similarity_distance": 0.3022230747890947,
                "icp_fitness_score": 1.0,
                "generation_error": null,
                "check_error": "AlignedBBoxCheck: Final Aligned vs Ref BBox Dims Diff (Sorted): ['0.0051', '0.5102', '0.0113'] exceeds tolerance 0.5",
                "scad_generation_success": true,
                "render_success": true,
                "render_status_detail": "Success",
                "geometry_check_orchestration_success": true,
                "individual_geometry_checks_passed": false,
                "individual_check_statuses": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": false
                },
                "geometry_check_error_detail": "AlignedBBoxCheck: Final Aligned vs Ref BBox Dims Diff (Sorted): ['0.0051', '0.5102', '0.0113'] exceeds tolerance 0.5",
                "overall_pipeline_success": false,
                "similarity_distance_detail": "0.3022"
            },
            {
                "task_id": "task4",
                "model_name": "gemini-2.0-flash",
                "task_description": "I\u2019m building a metal pin. It\u2019s a single part created using 3 operations.\nFirst, for the head of the pin, it\u2019s a simple cylinder. The cylinder is 35 mm in diameter and 20mm thick. Then for the shaft of the pin, there\u2019s another cylinder that\u2019s 20mm in diameter and 60mm long. So the total length of the metal pin (head + shaft) is 80mm.\nFinally, there\u2019s a chamfer on the head of the pin, on the top of it. In other words, if the pin was sitting on its head with the shaft in the sky, the chambered edge of the head would be towards the ground. The chamfer is 2mm in size (the edge length of the chamfer).",
                "reference_stl_path": "./reference/task4.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nI\u2019m building a metal pin. It\u2019s a single part created using 3 operations.\nFirst, for the head of the pin, it\u2019s a simple cylinder. The cylinder is 35 mm in diameter and 20mm thick. Then for the shaft of the pin, there\u2019s another cylinder that\u2019s 20mm in diameter and 60mm long. So the total length of the metal pin (head + shaft) is 80mm.\nFinally, there\u2019s a chamfer on the head of the pin, on the top of it. In other words, if the pin was sitting on its head with the shaft in the sky, the chambered edge of the head would be towards the ground. The chamfer is 2mm in size (the edge length of the chamfer).\n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-2.0-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-05T19:28:10.464641",
                "output_scad_path": "results/20250405_192806/scad/task4_google_gemini_2.0_flash.scad",
                "output_stl_path": "results/20250405_192806/stl/task4_google_gemini_2.0_flash.stl",
                "output_summary_json_path": "results/20250405_192806/stl/task4_google_gemini_2.0_flash_summary.json",
                "render_status": "Success",
                "render_duration_seconds": 0.07063102722167969,
                "render_error_message": null,
                "checks": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometric_similarity_distance": 0.22696369785240533,
                "icp_fitness_score": 1.0,
                "generation_error": null,
                "check_error": null,
                "scad_generation_success": true,
                "render_success": true,
                "render_status_detail": "Success",
                "geometry_check_orchestration_success": true,
                "individual_geometry_checks_passed": true,
                "individual_check_statuses": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometry_check_error_detail": null,
                "overall_pipeline_success": true,
                "similarity_distance_detail": "0.2270"
            },
            {
                "task_id": "task5",
                "model_name": "gemini-2.0-flash",
                "task_description": "This is a rectangular prism (a 50x50mm square extruded by 100mm) that has a half-circle (diameter 25mm) channel on one of the 4 long sides of the prism.",
                "reference_stl_path": "./reference/task5.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nThis is a rectangular prism (a 50x50mm square extruded by 100mm) that has a half-circle (diameter 25mm) channel on one of the 4 long sides of the prism.\n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-2.0-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-05T19:28:14.828699",
                "output_scad_path": "results/20250405_192806/scad/task5_google_gemini_2.0_flash.scad",
                "output_stl_path": "results/20250405_192806/stl/task5_google_gemini_2.0_flash.stl",
                "output_summary_json_path": "results/20250405_192806/stl/task5_google_gemini_2.0_flash_summary.json",
                "render_status": "Success",
                "render_duration_seconds": 0.05494093894958496,
                "render_error_message": null,
                "checks": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometric_similarity_distance": 1.305690160638658,
                "icp_fitness_score": 0.84152,
                "generation_error": null,
                "check_error": null,
                "scad_generation_success": true,
                "render_success": true,
                "render_status_detail": "Success",
                "geometry_check_orchestration_success": true,
                "individual_geometry_checks_passed": true,
                "individual_check_statuses": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometry_check_error_detail": null,
                "overall_pipeline_success": false,
                "similarity_distance_detail": "1.3057"
            },
            {
                "task_id": "task6",
                "model_name": "gemini-2.0-flash",
                "task_description": "This is a rectangular plate with a single hole with a counterbore.\nThe rectangular prism is 20mm wide and 40mm long with 5mm thickness.\nThe hole is 4mm in diameter. Looking down at the plate the centerpoint of the circle is 5mm from one of the long edges and its centered in the other direction (10mm from either side).\nThe counterbore is 8mm in diameter and is cut 2mm down into the plate.",
                "reference_stl_path": "./reference/task6.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nThis is a rectangular plate with a single hole with a counterbore.\nThe rectangular prism is 20mm wide and 40mm long with 5mm thickness.\nThe hole is 4mm in diameter. Looking down at the plate the centerpoint of the circle is 5mm from one of the long edges and its centered in the other direction (10mm from either side).\nThe counterbore is 8mm in diameter and is cut 2mm down into the plate.\n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-2.0-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-05T19:28:16.156268",
                "output_scad_path": "results/20250405_192806/scad/task6_google_gemini_2.0_flash.scad",
                "output_stl_path": "results/20250405_192806/stl/task6_google_gemini_2.0_flash.stl",
                "output_summary_json_path": "results/20250405_192806/stl/task6_google_gemini_2.0_flash_summary.json",
                "render_status": "Success",
                "render_duration_seconds": 0.06103992462158203,
                "render_error_message": null,
                "checks": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometric_similarity_distance": 0.1079208359356435,
                "icp_fitness_score": 1.0,
                "generation_error": null,
                "check_error": null,
                "scad_generation_success": true,
                "render_success": true,
                "render_status_detail": "Success",
                "geometry_check_orchestration_success": true,
                "individual_geometry_checks_passed": true,
                "individual_check_statuses": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometry_check_error_detail": null,
                "overall_pipeline_success": true,
                "similarity_distance_detail": "0.1079"
            },
            {
                "task_id": "task7",
                "model_name": "gemini-2.0-flash",
                "task_description": "This is a hollow torus, or a circular pipe. The hollow, circular section is 10mm in outer diameter and is 2mm in thickness. The total, outer diameter of the torus is 60mm. (40mm inner diameter).",
                "reference_stl_path": "./reference/task7.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nThis is a hollow torus, or a circular pipe. The hollow, circular section is 10mm in outer diameter and is 2mm in thickness. The total, outer diameter of the torus is 60mm. (40mm inner diameter).\n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-2.0-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-05T19:28:18.105671",
                "output_scad_path": "results/20250405_192806/scad/task7_google_gemini_2.0_flash.scad",
                "output_stl_path": null,
                "output_summary_json_path": null,
                "render_status": "Compile Error",
                "render_duration_seconds": 0.03394007682800293,
                "render_error_message": "OpenSCAD failed with exit code 1. Stderr: ",
                "checks": {
                    "check_render_successful": null,
                    "check_is_watertight": null,
                    "check_is_single_component": null,
                    "check_bounding_box_accurate": null
                },
                "geometric_similarity_distance": null,
                "icp_fitness_score": null,
                "generation_error": null,
                "check_error": null,
                "scad_generation_success": true,
                "render_success": false,
                "render_status_detail": "Compile Error",
                "geometry_check_orchestration_success": false,
                "individual_geometry_checks_passed": false,
                "individual_check_statuses": {
                    "check_render_successful": "N/A (Render Fail)",
                    "check_is_watertight": "N/A (Render Fail)",
                    "check_is_single_component": "N/A (Render Fail)",
                    "check_bounding_box_accurate": "N/A (Render Fail)"
                },
                "geometry_check_error_detail": null,
                "overall_pipeline_success": false,
                "similarity_distance_detail": "N/A"
            },
            {
                "task_id": "task8",
                "model_name": "gemini-2.0-flash",
                "task_description": "This is a 20mm x 20mm x 80 mm solid rectangular prism. All 12 edges of the solid have a 1mm fillet.",
                "reference_stl_path": "./reference/task8.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nThis is a 20mm x 20mm x 80 mm solid rectangular prism. All 12 edges of the solid have a 1mm fillet.\n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-2.0-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-05T19:28:12.060090",
                "output_scad_path": "results/20250405_192806/scad/task8_google_gemini_2.0_flash.scad",
                "output_stl_path": "results/20250405_192806/stl/task8_google_gemini_2.0_flash.stl",
                "output_summary_json_path": "results/20250405_192806/stl/task8_google_gemini_2.0_flash_summary.json",
                "render_status": "Success",
                "render_duration_seconds": 0.04260611534118652,
                "render_error_message": null,
                "checks": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": false
                },
                "geometric_similarity_distance": 0.49702033754763175,
                "icp_fitness_score": 0.99988,
                "generation_error": null,
                "check_error": "AlignedBBoxCheck: Final Aligned vs Ref BBox Dims Diff (Sorted): ['0.8652', '0.9943', '0.8849'] exceeds tolerance 0.5",
                "scad_generation_success": true,
                "render_success": true,
                "render_status_detail": "Success",
                "geometry_check_orchestration_success": true,
                "individual_geometry_checks_passed": false,
                "individual_check_statuses": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": false
                },
                "geometry_check_error_detail": "AlignedBBoxCheck: Final Aligned vs Ref BBox Dims Diff (Sorted): ['0.8652', '0.9943', '0.8849'] exceeds tolerance 0.5",
                "overall_pipeline_success": false,
                "similarity_distance_detail": "0.4970"
            },
            {
                "task_id": "task9",
                "model_name": "gemini-2.0-flash",
                "task_description": "This is a 50mm x 50mm x 50mm box with 5mm thick walls (and no top). You can create this box by creating a cube and then cutting down from the top a 40mm x 40mm square. ",
                "reference_stl_path": "./reference/task9.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nThis is a 50mm x 50mm x 50mm box with 5mm thick walls (and no top). You can create this box by creating a cube and then cutting down from the top a 40mm x 40mm square. \n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-2.0-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-05T19:28:13.496558",
                "output_scad_path": "results/20250405_192806/scad/task9_google_gemini_2.0_flash.scad",
                "output_stl_path": "results/20250405_192806/stl/task9_google_gemini_2.0_flash.stl",
                "output_summary_json_path": "results/20250405_192806/stl/task9_google_gemini_2.0_flash_summary.json",
                "render_status": "Success",
                "render_duration_seconds": 0.055197954177856445,
                "render_error_message": null,
                "checks": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometric_similarity_distance": 0.3327768004272705,
                "icp_fitness_score": 1.0,
                "generation_error": null,
                "check_error": null,
                "scad_generation_success": true,
                "render_success": true,
                "render_status_detail": "Success",
                "geometry_check_orchestration_success": true,
                "individual_geometry_checks_passed": true,
                "individual_check_statuses": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true
                },
                "geometry_check_error_detail": null,
                "overall_pipeline_success": true,
                "similarity_distance_detail": "0.3328"
            }
        ]
    }
}