{
    "run_id": "minitest_run_4",
    "meta_statistics": {
        "gemini-1.5-flash": {
            "total_tasks": 2,
            "scad_gen_success_count": 2,
            "render_success_count": 2,
            "geo_check_run_success_count": 2,
            "all_geo_checks_passed_count": 1,
            "overall_pipeline_success_count": 1,
            "volume_passed_count": 1,
            "hausdorff_passed_count": 1,
            "watertight_passed_count": 2,
            "single_comp_passed_count": 2,
            "bbox_passed_count": 1,
            "scad_gen_success_rate": 100.0,
            "render_success_rate_rel": 100.0,
            "geo_check_run_success_rate_rel": 100.0,
            "all_geo_checks_passed_rate_rel": 50.0,
            "volume_check_pass_rate_rel": 50.0,
            "hausdorff_check_pass_rate_rel": 50.0,
            "overall_pipeline_success_rate": 50.0,
            "average_chamfer_distance": 0.21863727560868623,
            "median_chamfer_distance": 0.21863727560868623,
            "stdev_chamfer_distance": 0.18294044860242184,
            "average_hausdorff_99p_distance": 0.5927779221349201,
            "median_hausdorff_99p_distance": 0.5927779221349201,
            "stdev_hausdorff_99p_distance": 0.4962179808610796,
            "average_volume_diff_percent": 14.93213461287138,
            "median_volume_diff_percent": 14.93213461287138,
            "stdev_volume_diff_percent": 20.511378976865327
        }
    },
    "results_by_model": {
        "gemini-1.5-flash": [
            {
                "task_id": "task2",
                "model_name": "gemini-1.5-flash",
                "task_description": "This is a 3mm thickness rectangular plate. The plate is 18mm x 32mm in dimension.\nWhen looking down at the plate, it has two holes that are drilled through it.\nIn the bottom left of the plate, there\u2019s a hole with a centerpoint that is 3mm from the short (18mm) side and 3 mm from the long (32mm) side. This hole has a diameter of 2mm\nIn roughly the top left corner of plate, there\u2019s a hole of diameter 3mm. It\u2019s center point is 8mm from the short side (18mm side) and 6mm away from the long (32mm) side.",
                "reference_stl_path": "./reference/task2.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nThis is a 3mm thickness rectangular plate. The plate is 18mm x 32mm in dimension.\nWhen looking down at the plate, it has two holes that are drilled through it.\nIn the bottom left of the plate, there\u2019s a hole with a centerpoint that is 3mm from the short (18mm) side and 3 mm from the long (32mm) side. This hole has a diameter of 2mm\nIn roughly the top left corner of plate, there\u2019s a hole of diameter 3mm. It\u2019s center point is 8mm from the short side (18mm side) and 6mm away from the long (32mm) side.\n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-1.5-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-07T10:00:46.510420",
                "output_scad_path": "results/minitest_run_4/scad/task2_google_gemini_1.5_flash.scad",
                "output_stl_path": "results/minitest_run_4/stl/task2_google_gemini_1.5_flash.stl",
                "output_summary_json_path": "results/minitest_run_4/stl/task2_google_gemini_1.5_flash_summary.json",
                "render_status": "Success",
                "render_duration_seconds": 0.04993629455566406,
                "render_error_message": null,
                "checks": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true,
                    "check_volume_passed": true,
                    "check_hausdorff_passed": true
                },
                "geometric_similarity_distance": 0.0892788438486047,
                "icp_fitness_score": 1.0,
                "hausdorff_99p_distance": 0.24189882292135426,
                "reference_volume_mm3": 1697.5457209369094,
                "generated_volume_mm3": 1704.8179974153054,
                "reference_bbox_mm": [
                    3.0,
                    18.0,
                    32.0
                ],
                "generated_bbox_aligned_mm": [
                    3.0010224045406706,
                    18.00368011911012,
                    32.0019808036798
                ],
                "generation_error": null,
                "check_error": null,
                "scad_generation_success": true,
                "individual_check_statuses": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": true,
                    "check_volume_passed": true,
                    "check_hausdorff_passed": true
                },
                "render_success": true,
                "geometry_check_run_success": true,
                "all_geometry_checks_passed": true,
                "chamfer_check_passed": true,
                "overall_pipeline_success": true,
                "hausdorff_99p_distance_detail": "0.2419",
                "volume_reference_detail": "1697.55",
                "volume_generated_detail": "1704.82",
                "bbox_reference_detail": "3.00, 18.00, 32.00",
                "bbox_generated_aligned_detail": "3.00, 18.00, 32.00",
                "chamfer_distance_detail": "0.0893",
                "render_status_detail": "Success",
                "geometry_check_error_detail": null
            },
            {
                "task_id": "task1",
                "model_name": "gemini-1.5-flash",
                "task_description": "A simple hex nut without the threads modeled. The nut has a hexagonal shape with a hole in the center of the hexagonal shape. The hexagon is 10mm wide (flat size to flat side). The hole diameter through the center of the hexagon is 5mm. The thickness of the nut is 5mm.",
                "reference_stl_path": "./reference/task1.stl",
                "prompt_used": "Create a valid OpenSCAD script that models the following 3D object, described below. The code should define a complete 3D model that closely matches the description.\n\nA simple hex nut without the threads modeled. The nut has a hexagonal shape with a hole in the center of the hexagonal shape. The hexagon is 10mm wide (flat size to flat side). The hole diameter through the center of the hexagon is 5mm. The thickness of the nut is 5mm.\n\nIMPORTANT: Create only a SINGLE part/model in this script. Do not include multiple unconnected components.\n\nReminders:\n- Ensure the model is manifold and watertight\n- Use appropriate operations as needed\n- Define the model at the origin (0,0,0)\n- Include helpful comments in your code\n- Do not include example usage or test code\n- Do not include explanations outside of code comments",
                "llm_config": {
                    "provider": "google",
                    "name": "gemini-1.5-flash",
                    "temperature": 0.4,
                    "max_tokens": 15000
                },
                "timestamp_utc": "2025-04-07T10:00:48.763204",
                "output_scad_path": "results/minitest_run_4/scad/task1_google_gemini_1.5_flash.scad",
                "output_stl_path": "results/minitest_run_4/stl/task1_google_gemini_1.5_flash.stl",
                "output_summary_json_path": "results/minitest_run_4/stl/task1_google_gemini_1.5_flash_summary.json",
                "render_status": "Success",
                "render_duration_seconds": 0.03621506690979004,
                "render_error_message": null,
                "checks": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": false,
                    "check_volume_passed": false,
                    "check_hausdorff_passed": false
                },
                "geometric_similarity_distance": 0.3479957073687678,
                "icp_fitness_score": 1.0,
                "hausdorff_99p_distance": 0.943657021348486,
                "reference_volume_mm3": 334.9735592138611,
                "generated_volume_mm3": 236.37117852992233,
                "reference_bbox_mm": [
                    5.0,
                    10.766426086425781,
                    11.410706520080566
                ],
                "generated_bbox_aligned_mm": [
                    5.0075093612392205,
                    9.643112754340091,
                    9.680729657570708
                ],
                "generation_error": null,
                "check_error": "HausdorffCheck: 99p distance 0.9437 mm exceeds threshold 0.5 mm; AlignedBBoxCheck: Final Aligned vs Ref BBox Dims Diff (Sorted): ['0.0075', '1.1233', '1.7300'] exceeds tolerance 0.5",
                "scad_generation_success": true,
                "individual_check_statuses": {
                    "check_render_successful": true,
                    "check_is_watertight": true,
                    "check_is_single_component": true,
                    "check_bounding_box_accurate": false,
                    "check_volume_passed": false,
                    "check_hausdorff_passed": false
                },
                "render_success": true,
                "geometry_check_run_success": true,
                "all_geometry_checks_passed": false,
                "chamfer_check_passed": true,
                "overall_pipeline_success": false,
                "hausdorff_99p_distance_detail": "0.9437",
                "volume_reference_detail": "334.97",
                "volume_generated_detail": "236.37",
                "bbox_reference_detail": "5.00, 10.77, 11.41",
                "bbox_generated_aligned_detail": "5.01, 9.64, 9.68",
                "chamfer_distance_detail": "0.3480",
                "render_status_detail": "Success",
                "geometry_check_error_detail": "HausdorffCheck: 99p distance 0.9437 mm exceeds threshold 0.5 mm; AlignedBBoxCheck: Final Aligned vs Ref BBox Dims Diff (Sorted): ['0.0075', '1.1233', '1.7300'] exceeds tolerance 0.5"
            }
        ]
    }
}